export default [{
    rules: {
        "quotes": ["error", "single"],
        "semi": ["error", "always"],
        "brace-style": ["error", "1tbs"],
        "camelcase": ["error", {}],
        "comma-style": ["error", "last"],
        "func-call-spacing": ["error", "never"],
        "implicit-arrow-linebreak": ["error", "beside"],
        "indent": ["error", 4],
        "key-spacing": ["error", {}],
        "keyword-spacing": ["error"],
        "max-len": ["error", {
            "code": 120,
        }],
        "no-lonely-if": ["error"],
        "no-trailing-spaces": ["error"],
        "object-curly-spacing": ["error"],
        "space-before-blocks": ["error"],
        "space-in-parens": ["error"],
        "space-infix-ops": ["error"],
        "space-unary-ops": ["error"],
        "spaced-comment": ["error"],
    },
}];